<?php
if(!isset($ROOT_PATH)){
    $ROOT_PATH=dirname(__FILE__, 2);
}
if(!isset($TMP_PATH)){
    $TMP_PATH=sys_get_temp_dir();
}

return [
    '#rootPath'=>$ROOT_PATH,
    '#libPath'=>$ROOT_PATH.'/lib',
    '#commonPath'=>$ROOT_PATH.'/common',
    '#templatesPath'=>$ROOT_PATH.'/frontend/templates',
    '#wwwURL'=>'../../www',
    '#cookiePath'=>'/',
    '#secret'=>'gJUYGo87fsghgO*sdfsGftu',
    '@html'=>[
        '#encoding'=>'utf-8',
        '#title'=>'Proctor'
    ],
    '@lang'=>[
        '#sourceLang'=>'en',
        '#defaultTarget'=>'ru-RU',
        '#langBasePath'=>$ROOT_PATH.'/lang'
    ],
    '@log'=>[
        //'#targetType'=>'html_end',
        '#targetType'=>'file',
        '#logMode'=>255,
        '#logCookiePath'=>'/',
        '#clientTokenName'=>'DOQ_LOG_CLIENT',
        '#pageloadTokenName'=>'DOQ_LOG_PAGELOAD',
        '#logsPath'=>"{$TMP_PATH}/doq/logs"
    ],
    '@modules'=>[
        'auth'    =>['actions'=>['default'=>'auth_status.php']],
        'products'=>['actions'=>['default'=>'products_list.php']]
    ],
    '@cache'=>[
        '@providers'=>[
             'SerialFileCache'=>[
                #'#cachePath'=>$ROOT_PATH.'/runtime/caches',
                '#cachePath'=>"{$TMP_PATH}/doq/caches",
            ]
        ],
        '@targets'=>[
            'queries'=>[
                '#provider'=>'SerialFileCache',
                '#targetFolder'=>'queries',
                '#filePrefix'=>'q_',
                '#fileSuffix'=>'.q.txt',
                '#forceCreateFolder'=>1,
                '#alwaysRebuild'=>0
            ],
            'writers'=>[
                '#provider'=>'SerialFileCache',
                '#targetFolder'=>'writers',
                '#filePrefix'=>'w_',
                '#fileSuffix'=>'.w.txt',
                '#forceCreateFolder'=>1,
                '#alwaysRebuild'=>0
            ],
            'templates'=>[
                '#provider'=>'SerialFileCache',
                '#targetFolder'=>'templates',
                '#filePrefix'=>'t_',
                '#fileSuffix'=>'.tmpls.txt',
                '#forceCreateFolder'=>1,
                '#alwaysRebuild'=>1,
                
            ]
        ]

    ],
    '@session'=>[
        '#sessionDataConnection'=>'MYSQL0', // база данных, в которых есть sys_signups(запросы на регистрацию), sys_users(зарегистрированные), sys_sessions (сессии), sys_client(браузеры), sys_form_nonces(токены для форм авторизации),
        '#autoApprove'=>'1' // автоматически переносить в список допущенных пользователей
    ],
    '@dataConnections'=>[
        'MYSQL0'=>[
            '@environments'=>[
                'DEVELOPMENT_PI'=>[
                    '#provider'=>'mysql',
                    '#debugLevel'=>'1',
                    '@params'=>[
                        'host'=>'127.0.0.1',
                        'port'=>'3306',
                        'dbase'=>'test',
                    ]
                ],
                'DEVELOPMENT'=>[
                    '#provider'=>'mysql',
                    '#debugLevel'=>'1',
                    '@params'=>[
                        'host'=>'127.0.0.1',
                        'port'=>'3306',
                        'dbase'=>'test',
                    ]
                ],
                '*'=>[
                    '#provider'=>'mysql',
                    '@params'=>[
                        'host'=>'127.0.0.1',
                        'port'=>'3306',
                        'dbase'=>'dbnavi',
                    ]
                ]
            ]
        ],
        'MYSQL1'=>[
            '#provider'=>'mysql',
            '@params'=>[
                'host'=>'95.191.130.173',
                'port'=>'8036',
                'dbase'=>'test',
            ]

        ],
        'localmem'=>[
            '#provider'=>'memory'
        ]
    ]
];
